server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql:commitments}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}
  jpa:
    open-in-view: false
  flyway:
    locations: classpath:/db/migration
    clean-on-validation-error: true
